CREATE DATABASE LMS;
show DATABASES;
use lms;
show tables;


CREATE TABLE User_Details (Id INT AUTO_INCREMENT NOT NULL,
						   Email_Id VARCHAR(50),
                           First_Name VARCHAR(50) NOT NULL,
                           Last_Name VARCHAR(50) NOT NULL,
                           Password VARCHAR(50),
                           Contact_Number VARCHAR(10),
                           Verified VARCHAR(50),
                           Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           Creator_User INT NOT NULL,
                           PRIMARY KEY (Id));

CREATE TABLE Hired_Candidate (Id INT NOT NULL,
							  First_Name VARCHAR(50),
                              Middle_Name VARCHAR(50),
                              Last_Name VARCHAR(50),
                              Email_Id VARCHAR(50),
                              Hired_City VARCHAR(50),
                              Degree VARCHAR(50),
                              Hired_Date DATE,
                              Mobile_Number VARCHAR(10),
                              Permanent_Pincode VARCHAR(10),
                              Hired_Lab VARCHAR(50),
                              Attitude VARCHAR(50),
                              Communication_Remark VARCHAR(10),
                              Knowledge_Remark VARCHAR(10),
                              Aggregate_Remark VARCHAR(10),
                              Status VARCHAR(50),
                              Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              Creator_User INT NOT NULL,
                              PRIMARY KEY (Id),
                              FOREIGN KEY (Creator_User) REFERENCES User_Details(Id));

CREATE TABLE Fellowship_Candidate (Id INT NOT NULL,
								   CIC_ID VARCHAR(20),
                                   First_Name VARCHAR(50),
								   Middle_Name VARCHAR(50),
								   Last_Name VARCHAR(50),
                                   Email_Id VARCHAR(50),
								   Hired_City VARCHAR(50),
								   Degree VARCHAR(50),
								   Hired_Date DATE,
								   Mobile_Number VARCHAR(10),
								   Permanent_Pincode VARCHAR(10),
								   Hired_Lab VARCHAR(50),
								   Attitude VARCHAR(50),
								   Communication_Remark VARCHAR(10),
								   Knowledge_Remark VARCHAR(10),
								   Aggregate_Remark VARCHAR(10),
                                   Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
								   Creator_User INT NOT NULL,
                                   Birth_Date DATE,
                                   Is_Birth_Date_Verified BOOLEAN,
                                   Parent_Name VARCHAR(50),
                                   Parent_Occupation VARCHAR(50),
                                   Parent_Mobile_Number VARCHAR(10),
                                   Parent_Annual_Salary LONG,
                                   Local_Address VARCHAR(255),
                                   Permanent_Address VARCHAR(255),
                                   Photo_Path VARCHAR(50),
                                   Joining_Date DATE,
                                   Candidate_Status VARCHAR(20),
                                   Personal_Information TEXT,
                                   Bank_Information TEXT,
                                   Educational_Information TEXT,
                                   Document_Status VARCHAR(50),
                                   Remark VARCHAR(50),
                                   PRIMARY KEY (Id),
                                   FOREIGN KEY (Creator_User) REFERENCES User_Details(Id));
                                   
 CREATE TABLE Candidate_Bank_Details (Id INT NOT NULL,
									  Candidate_Id INT NOT NULL,
                                      Name VARCHAR(100),
                                      Account_Number VARCHAR(20),
                                      Is_Account_Number_Verified BOOLEAN,
                                      Ifsc_Code VARCHAR(20),
                                      Is_Ifsc_Code_Verified BOOLEAN,
                                      Pan_Number VARCHAR(20),
                                      Is_Pan_Number_Verified BOOLEAN,
                                      Addhar_Number VARCHAR(20),
                                      Is_Addhar_Number_Verified BOOLEAN,
                                      Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      Creator_User INT NOT NULL,
                                      PRIMARY KEY (Id),
									  FOREIGN KEY (Creator_User) REFERENCES User_Details(Id),
                                      FOREIGN KEY (Candidate_Id) REFERENCES Fellowship_Candidate(Id));                                  
                                   
CREATE TABLE Candidate_Qualification (Id INT NOT NULL,
									  Candidate_Id INT NOT NULL,
									  Diploma VARCHAR(100),
                                      Degree_Name VARCHAR(100),
                                      Is_Degree_Name_Verified BOOLEAN,
                                      Employee_Decipline VARCHAR(100),
                                      Is_Employee_Decipline_Verified BOOLEAN,
                                      Passing_Year INT,
                                      Is_Passing_Year_Verified BOOLEAN,
                                      Final_Year_Percentage FLOAT,
                                      Is_Final_Year_Percentage_Verified BOOLEAN,
                                      Training_Institute VARCHAR(100),
                                      Is_Training_Institute_Verified BOOLEAN,
                                      Training_Duration_Month VARCHAR(50),
                                      Is_Training_Duration_Month_Verified BOOLEAN,
                                      Other_Training VARCHAR(50),
                                      Is_Other_Training_Verified BOOLEAN,
                                      Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      Creator_User INT NOT NULL,
                                      PRIMARY KEY (Id),
                                      FOREIGN KEY (Creator_User) REFERENCES User_Details(Id),
                                      FOREIGN KEY (Candidate_Id) REFERENCES Fellowship_Candidate(Id)); 
                                     
CREATE TABLE Candidate_Documents (Id INT NOT NULL,
								  Candidate_Id INT NOT NULL,
                                  Doc_Type VARCHAR(50),
                                  Doc_Path VARCHAR(50),
                                  Status VARCHAR(50),
                                  Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
								  Creator_User INT NOT NULL,
								  PRIMARY KEY (Id),
                                  FOREIGN KEY (Creator_User) REFERENCES User_Details(Id),
                                  FOREIGN KEY (Candidate_Id) REFERENCES Fellowship_Candidate(Id));   
                                 
CREATE TABLE Company (Id INT NOT NULL,
					  Name VARCHAR(100),
                      Address VARCHAR(255),
                      Location VARCHAR(20),
                      Status VARCHAR(50),
                      Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
					  Creator_User INT NOT NULL,
					  PRIMARY KEY (Id),
					  FOREIGN KEY (Creator_User) REFERENCES User_Details(Id));                                 
    
CREATE TABLE Maker_Program (Id INT NOT NULL,
							Program_Name VARCHAR(50),
                            Program_Type VARCHAR(50),
                            Program_Link VARCHAR(100),
                            Tech_Stack_Id INT NOT NULL,
                            Tech_Type_Id INT NOT NULL,
                            Is_Program_Approved BOOLEAN,
                            Description VARCHAR(255),
                            Status VARCHAR(50),
                            Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
						    Creator_User INT NOT NULL,
							PRIMARY KEY (Id),
                            FOREIGN KEY (Creator_User) REFERENCES User_Details(Id),
                            FOREIGN KEY (Tech_Stack_Id) REFERENCES Tech_Stack(Id),
                            FOREIGN KEY (Tech_Type_Id) REFERENCES Tech_Type(Id));    
    
CREATE TABLE App_Parameters (Id INT NOT NULL,
							 Key_Type VARCHAR(50),
                             Key_Value VARCHAR(20),
                             Key_Text VARCHAR(20),
                             Cur_Status VARCHAR(20),
							 Lastupd_User VARCHAR(20),
                             Lastupd_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
						     Creator_User INT NOT NULL,
                             Seq_Num INT,
                             PRIMARY KEY (Id),
                             FOREIGN KEY (Creator_User) REFERENCES User_Details(Id));
 
CREATE TABLE Mentor (Id INT NOT NULL,
					 Name VARCHAR(50),
                     Mentor_Type VARCHAR(20),
                     Lab_Id INT NOT NULL,
                     Status VARCHAR(20),
                     Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
					 Creator_User INT NOT NULL,
					 PRIMARY KEY (Id),
                     FOREIGN KEY (Creator_User) REFERENCES User_Details(Id),
                     FOREIGN KEY (Lab_Id) REFERENCES Lab(Id)); 
                     
CREATE TABLE Mentor_Ideation_Map (Id INT NOT NULL,
								  Parent_Mentor_Id INT,
                                  Mentor_Id INT,
                                  Status VARCHAR(20),
                                  Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
								  Creator_User INT NOT NULL,
                                  PRIMARY KEY (Id),
                                  FOREIGN KEY (Creator_User) REFERENCES User_Details(Id),
                                  FOREIGN KEY (Parent_Mentor_Id) REFERENCES Mentor(Id),
                                  FOREIGN KEY (Mentor_Id) REFERENCES Mentor(Id)); 
                                  
CREATE TABLE Mentor_Tech_Stack (Id INT NOT NULL,
								Mentor_Id INT NOT NULL,
                                Tech_Stack_Id INT NOT NULL,
                                Status VARCHAR(20),
                                Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
								Creator_User INT NOT NULL,
                                PRIMARY KEY (Id),
                                FOREIGN KEY (Creator_User) REFERENCES User_Details(Id),
                                FOREIGN KEY (Mentor_Id) REFERENCES Mentor(Id),
                                FOREIGN KEY (Tech_Stack_Id) REFERENCES Tech_Stack(Id));                                  
 
CREATE TABLE Tech_Stack (Id INT NOT NULL,
						 Tech_Name VARCHAR(100),
                         Image_Path VARCHAR(100),
                         Framework VARCHAR(20),
                         Cur_Status VARCHAR(20),
                         Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
					     Creator_User INT NOT NULL,
						 PRIMARY KEY (Id),
                         FOREIGN KEY (Creator_User) REFERENCES User_Details(Id));                     
 
CREATE TABLE Tech_Type (Id INT NOT NULL,
						Type_Name VARCHAR(100),
                        Cur_Status VARCHAR(20),
                        Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
						Creator_User INT NOT NULL,
						PRIMARY KEY (Id),
                        FOREIGN KEY (Creator_User) REFERENCES User_Details(Id)); 
 
CREATE TABLE Lab (Id INT NOT NULL,
				  Name VARCHAR(100),
                  Location VARCHAR(20),
                  Address VARCHAR(100),
                  Status VARCHAR(20),
                  Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				  Creator_User INT NOT NULL,
				  PRIMARY KEY (Id),
                  FOREIGN KEY (Creator_User) REFERENCES User_Details(Id)); 
 
CREATE TABLE Lab_Threshold (Id INT NOT NULL,
							Lab_Id INT NOT NULL,
                            Lab_Capacity INT,
							Lead_Threshold INT,
                            Ideation_Engg_Threshold INT,
                            Buddy_Engg_Threshold INT,
                            Status VARCHAR(20),
                            Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				            Creator_User INT NOT NULL,
							PRIMARY KEY (Id),
                            FOREIGN KEY (Creator_User) REFERENCES User_Details(Id),
                            FOREIGN KEY (Lab_Id) REFERENCES Lab(Id)); 
 
CREATE TABLE Company_Requirement (Id INT NOT NULL,
								  Company_Id INT NOT NULL,
                                  Requested_Month DATE,
                                  City VARCHAR(20),
                                  Is_Doc_Verification BOOLEAN,
                                  Requirement_Doc_Path VARCHAR(50),
                                  No_Of_Engg INT,
                                  Tech_Stack_Id INT,
                                  Tech_Type_Id INT,
                                  Maker_Program_Id INT,
                                  Lead_Id INT,
                                  Ideation_Engg_Id INT,
                                  Buddy_Engg_Id INT,
                                  Special_Remark VARCHAR(20),
                                  Status VARCHAR(20),
                                  Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
								  Creator_User INT NOT NULL,
								  PRIMARY KEY (Id),
                                  FOREIGN KEY (Creator_User) REFERENCES User_Details(Id),
                                  FOREIGN KEY (Company_Id) REFERENCES Company(Id),
                                  FOREIGN KEY (Tech_Stack_Id) REFERENCES Tech_Stack(Id),
                                  FOREIGN KEY (Tech_Type_Id) REFERENCES Tech_Type(Id),
                                  FOREIGN KEY (Maker_Program_Id) REFERENCES Maker_Program(Id),
                                  FOREIGN KEY (Lead_Id) REFERENCES Mentor(Id),
                                  FOREIGN KEY (Ideation_Engg_Id) REFERENCES Mentor_Ideation_Map(Id),
                                  FOREIGN KEY (Buddy_Engg_Id) REFERENCES Mentor(Id)); 
 
CREATE TABLE Candidate_Stack_Assignment (Id INT NOT NULL,
										 Requirement_Id INT,
                                         Candidate_Id INT,
                                         Assign_Date DATE,
                                         Complete_Date DATE,
                                         Status VARCHAR(20),
                                         Creator_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
										 Creator_User INT NOT NULL,
										 PRIMARY KEY (Id),
                                         FOREIGN KEY (Creator_User) REFERENCES User_Details(Id),
                                         FOREIGN KEY (Requirement_Id) REFERENCES Company_Requirement(Id),
                                         FOREIGN KEY (Candidate_Id) REFERENCES Fellowship_Candidate(Id)); 
 
 
 
 
 
 
 
 
                                   
                                   
			
                                   
